"""Added meta table

Revision ID: 2cab0ca170e2
Revises: 
Create Date: 2022-11-26 15:25:38.928340

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '2cab0ca170e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'meta',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('hash', sa.VARBINARY(32), nullable=False),
        sa.Column('path', sa.VARCHAR(260), nullable=False),
        sa.Column('size', sa.BIGINT(), nullable=False),
        sa.Column('extension', sa.VARCHAR(6), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta')
    # ### end Alembic commands ###
