"""Added 'imports' and 'exports' to meta table

Revision ID: 70cd146d86a4
Revises: ca569cb9b2cc
Create Date: 2022-12-05 14:36:49.792958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70cd146d86a4'
down_revision = 'ca569cb9b2cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta', sa.Column('imports', sa.INT(), nullable=True))
    op.add_column('meta', sa.Column('exports', sa.INT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta', 'exports')
    op.drop_column('meta', 'imports')
    # ### end Alembic commands ###
