"""Added 'arch' column to Meta table

Revision ID: ca569cb9b2cc
Revises: 2cab0ca170e2
Create Date: 2022-12-05 00:47:01.205973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca569cb9b2cc'
down_revision = '2cab0ca170e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'meta', sa.Column('arch', sa.VARCHAR(length=16), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta', 'arch')
    # ### end Alembic commands ###
